id: I7762E19E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T15:04:47+00:00'
last_modified: '2022-06-08T01:15:00.992928+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS17499
  title: གསུང་རྩོམ། དཀོན་མཆོག་རྒྱ་མཚོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    899F:
      image_group_id: I8LS17506
      title: ''
      total_pages: 320
      order: 1
      base_file: 899F.txt
    '1030':
      image_group_id: I8LS17507
      title: ''
      total_pages: 356
      order: 2
      base_file: 1030.txt
    4AA5:
      image_group_id: I8LS17508
      title: ''
      total_pages: 219
      order: 3
      base_file: 4AA5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
